Fix error while adding coco_category_list
Orginal function coco.add_3fdc_from_coco_category_list(coco_category_list) caused error: 'Coco' object has no attribute 'add_3fdc_from_coco_category_list'. 
It doesn't exist in the recommended version of the sahi library 0.8.19. Changing following line for coco.add_categories_from_coco_category_list(coco_category_list) fix the problem